#00. Pytorch Fundamentals
## Resource notebook: https://www.learpytorch.io/00_pytorch_fundamentals/


In [1]:
import torch
print(torch.__version__)

2.2.1+cu121


In [2]:
# tensors
# creating scalar tensors

scalar = torch.tensor(7)
# getting data out of tensor
scalar.item()

7

In [3]:
# vector
vector = torch.tensor([7,7])
vector.ndim

1

In [4]:
MATRIX = torch.tensor([[7,7],
                       [9,10]])
MATRIX.ndim

2

In [5]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,3,5]
                        ]])
TENSOR.shape

torch.Size([1, 3, 3])

In [6]:
# Random tensors
# creating ransom tensors
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.3826, 0.7925, 0.0825, 0.2856],
        [0.6192, 0.9274, 0.7279, 0.1390],
        [0.8705, 0.3944, 0.5005, 0.4662]])

In [7]:
# ranson tensor to image size
random_image_tensor = torch.rand(size = (224,224,3))
random_image_tensor.shape

torch.Size([224, 224, 3])

In [8]:
# zeros and one
zero = torch.zeros(3,4)
zero
ones = torch.ones(3,4)
ones.dtype

torch.float32

In [9]:
# creating a range of tensors

# range
one_to_ten = torch.arange(start = 1, end=1000, step = 77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [10]:
# tensors like creation
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# dealing with tensor_datatypes

float_32_tensor = torch.tensor([3.,6.,9.],dtype = None
                               ,device=None
                               , requires_grad=False
                               )
float_32_tensor.dtype

torch.float32

In [12]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [13]:
# performing multiplication of flat 32 and 16 tensors
sampled_tensor = float_32_tensor*float_16_tensor
sampled_tensor.dtype

torch.float32

In [14]:
# in32 tensor
int32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [15]:
float_32_tensor * int32_tensor

tensor([ 9., 36., 81.])

In [16]:
# getting information from tensors
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7921, 0.0632, 0.9619, 0.1100],
        [0.5440, 0.7402, 0.7463, 0.7726],
        [0.5184, 0.9686, 0.4966, 0.5744]])

In [17]:
print(some_tensor)
print(f'Datatype of tensor:{some_tensor.dtype}')
print(f'Shape of tensor:{some_tensor.shape}')
print(f'Device tensor is on:{some_tensor.device}')

tensor([[0.7921, 0.0632, 0.9619, 0.1100],
        [0.5440, 0.7402, 0.7463, 0.7726],
        [0.5184, 0.9686, 0.4966, 0.5744]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


In [18]:
# manipulating tensors
# tensor operations include, addition, subtraction, multiplication, mat multiplication

tensor = torch.tensor([1,2,3])
tensor*10

tensor([10, 20, 30])

In [19]:
print(tensor,'*', tensor)
print(f'Equals: {torch.matmul(tensor,tensor)}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: 14


In [20]:
# creating a tensor using arange

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
x.min(),x.max(),torch.mean(x.type(torch.float32)), x.sum()

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [22]:
x.argmax()

tensor(9)

In [23]:
# tensor reshaping, squezing and unsqueezing tensors

# reshape reshapes an input tensor ti a defined shape

x = torch.arange(1.,10.)
x.shape


torch.Size([9])

In [24]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [25]:
z = x.view(1,9)
x,z.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([1, 9]))

In [26]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [27]:
x_original  = torch.rand(size = (224,224,3))
# permuting the data
x_permuted = x_original.permute(2,0,1)

x_permuted.shape, x_original.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

In [28]:
# selecting data from tensors with indexing
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [29]:
# indexing on new tensor
x[:,:,2].squeeze()

tensor([3, 6, 9])

In [30]:
# working with pytorch with numpy
import numpy as np

In [31]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [32]:
tensor = torch.ones(7)

numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [33]:
# concept of reproducibility

# creating two random tensors

randon_tensor_A = torch.rand(3,4)
randon_tensor_B = torch.rand(3,4)
print(randon_tensor_A)
print(randon_tensor_B)
print(randon_tensor_A==randon_tensor_B)

tensor([[0.6642, 0.2650, 0.9577, 0.3100],
        [0.7614, 0.4009, 0.8688, 0.1460],
        [0.9570, 0.3693, 0.6658, 0.2344]])
tensor([[0.1532, 0.2134, 0.3447, 0.7126],
        [0.3400, 0.6393, 0.6506, 0.5850],
        [0.4860, 0.4675, 0.6076, 0.8302]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [34]:
# working with random seeds

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(
random_tensor_c == random_tensor_d )

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [35]:
# checking for GPU access

torch.cuda.is_available()


True

In [36]:
# setting up device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [37]:
tensor = torch.tensor([1,2,3])

print(tensor)

tensor([1, 2, 3])


In [40]:
# modev tensor to GPU if available

tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [42]:
# moving tensor's back to cpu
# if tensor on GPU cannot conver to numpy
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])